name: Node.js CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: [self-hosted, label-1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Frontend Syntax Check
      - name: Frontend Syntax Check
        run: |
          cd client
          find . -type f -name "*.js" -exec node --check {} \;

      # Backend Syntax Check
      - name: Backend Syntax Check
        run: |
          cd api
          find . -type f -name "*.js" -exec node --check {} \;
          
  gitleaks-scan:
    runs-on: [self-hosted, label-1]
    needs: compile
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Run Gitleaks on client
       uses: gitleaks/gitleaks-action@v2
       with:
        args: detect --source ./client --exit-code 1

     - name: Run Gitleaks on api
       uses: gitleaks/gitleaks-action@v2
       with:
        args: detect --source ./api --exit-code 1


      

    
